
dist:     xenial    # используем Ubuntu 16.04 LTS
sudo:     required  # используем Virtual Machine (а не Docker container)

language: cpp       
os:
    - linux
script:
   - git ls-files src/ | xargs clang-format -i && git diff --exit-code
   make
